name: ReactJS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buildanddeploy:

    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.gcp_credentials }}'

    - id: 'upload-files'
      uses: 'google-github-actions/upload-cloud-storage@main'
      with:
        path: 'build'
        destination: 'cooding-io/app/'
        parent: false
